apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cp4d-deployment
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: <repoURL>
    targetRevision: HEAD
    path: overlays/dev
  destination:
    namespace: cloud-pak-deployer
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true