apiVersion: batch/v1
kind: Job
metadata:
  name: cloud-pak-deployer-starter
  namespace: cloud-pak-deployer
  annotations:
      argocd.argoproj.io/hook: PostSync
      argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  # backoffLimit: 0
  template:
    metadata:
      labels:
        app: cloud-pak-deployer-start
    spec:
      restartPolicy: Never
      securityContext:
        runAsUser: 0
      serviceAccountName: cloud-pak-deployer-sa
      containers:
      - name: cloud-pak-deployer
        image: quay.io/cloud-pak-deployer/cloud-pak-deployer:latest
        imagePullPolicy: Always
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        command: ["/bin/sh","-xc"]
        args:
          - /cloud-pak-deployer/scripts/deployer/cpd-start-deployer.sh