apiVersion: batch/v1
kind: Job
metadata:
  name: cloud-pak-deployer-debug
  namespace: cloud-pak-deployer
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        app: cloud-pak-deployer-debug
    spec:
      serviceAccountName: cloud-pak-deployer-sa
      restartPolicy: Never
      securityContext:
        runAsUser: 0
      containers:
      - name: cloud-pak-deployer-debug
        image: quay.io/cloud-pak-deployer/cloud-pak-deployer:latest
        imagePullPolicy: Always
        env:
        - name: CONFIG_DIR
          value: /Data/cpd-config
        - name: STATUS_DIR
          value: /Data/cpd-status
        volumeMounts:
        - name: config-volume
          mountPath: /Data/cpd-config/config
        - name: status-volume
          mountPath: /Data/cpd-status
        command: ["/bin/sh","-xc"]
        args: 
          - sleep infinity
      volumes:
      - name: config-volume
        configMap:
          name: cloud-pak-deployer-config
      - name: status-volume
        persistentVolumeClaim:
          claimName: cloud-pak-deployer-status